variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "/certs"
    MYSQL_ROOT_PASSWORD: app
    MYSQL_USER: app
    MYSQL_PASSWORD: app
    MYSQL_DATABASE: shopware
    GIT_STRATEGY: clone
    GIT_DEPTH: 1
    ARTIFACTS_ROOT: "$CI_PROJECT_DIR/build/artifacts"
    DB_USER: "app"
    DB_PASSWORD: "app"
    DB_HOST: "mysql"
    DB_PORT: 3306
    DB_NAME: shopware
    SW_HOST: "localhost"
    SW_BASE_PATH: ""
    ELASTICSEARCH_HOST: elasticsearch

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - if: '$CI_COMMIT_BRANCH'

.composer-cache: &composer-cache
    key:
        files:
            - 'composer.lock'
            - 'recovery/common/composer.lock'
    paths:
        - 'vendor/'
        - 'recovery/common/vendor/'
        - 'vendor-bin/'
        - '.htaccess'
        - '.make.install.composer-dependencies'
    policy: pull-push

.npm-cache: &npm-cache
    key:
        files:
            - 'themes/package-lock.json'
            - 'themes/Frontend/Responsive/package-lock.json'
    paths:
        - 'themes/node_modules/'
        - 'themes/Frontend/Responsive/node_modules/'
        - '.make.install.npm-dependencies'
    policy: pull-push

stages:
    - Prepare Files
    - Static analysis
    - PHPUnit
    - End-to-end testing
    - Security
    - Build Image

default:
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.4

# Stage: Prepare Files

Install Required PHP Files:
    tags:
        - t3.nano
    stage: Prepare Files
    script:
        - make .make.install.composer-dependencies
    cache:
        <<: *composer-cache

Install Required JS Files:
    tags:
        - t3.nano
    image: node:alpine
    stage: Prepare Files
    before_script:
        - apk add --no-cache make bash
    script:
        - make .make.install.npm-dependencies
    cache:
        <<: *npm-cache

PHP analyze:
    tags:
        - m5.large
    cache:
        - <<: *composer-cache
          policy: pull
    stage: Static analysis
    before_script:
        - make init
    script:
        - make check-code
    services:
        -   name: mysql:5.7
            alias: mysql

JavaScript checks:
    tags:
        - t3.nano
    cache:
        - <<: *npm-cache
          policy: pull
    stage: Static analysis
    image: node:alpine
    before_script:
        - apk add bash make
    script:
        - make check-js-code
        - make test-jest

.phpunit_base:
    tags:
        - t3.medium
    cache:
        - <<: *composer-cache
          policy: pull
    before_script: # TODO: (SW-26726) Remove this and see if anything breaks.
        - sed -i -e "s;__ROOT__;$CI_PROJECT_DIR;g" /etc/nginx/sites-enabled/shopware.conf
        - /usr/bin/supervisord -c /etc/supervisord.conf &>/dev/null &
        # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27921#note_38132416
        - eval export DB_USER DB_PASSWORD DB_HOST DB_PORT DB_NAME SW_HOST SW_BASE_PATH ELASTICSEARCH_HOST
    stage: PHPUnit
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - make test-phpunit
    artifacts:
        expire_in: 1 week
        reports:
            junit: ${ARTIFACTS_ROOT}/test-log.xml

.phpunit_es_base:
    tags:
        - t3.medium
    extends: .phpunit_base
    script:
        - make init
        - make test-phpunit-elasticsearch

    artifacts:
        expire_in: 1 week
        reports:
            junit: ${ARTIFACTS_ROOT}/test-log.xml

Code Coverage:
    extends: .phpunit_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:8.0
    script:
        - make test-phpunit-coverage-cobertura
    artifacts:
        paths:
            - ${ARTIFACTS_ROOT}/*
        expire_in: 1 week
        reports:
            junit: ${ARTIFACTS_ROOT}/phpunit.junit.xml
            cobertura: ${ARTIFACTS_ROOT}/*.cobertura.xml
    parallel:
        matrix:
            - TESTSUITE: ['unit', 'functional']

Code Coverage Statistic:
    extends: .phpunit_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:8.0
    variables:
        TESTSUITE: 'all'
    script:
        - make test-phpunit-coverage-statistic | sed -E -n '1,/^\s*Lines:\s*([0-9]+(\.[0-9]+)?)%/ p' # See: https://gitlab.shopware.com/shopware/6/product/platform/-/blob/trunk/.gitlab/stages/02-unit.yml#L92
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'

PHP 7.4:
    extends: .phpunit_base

PHP 8.1:
    extends: .phpunit_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:8.1

MySQL 8.0:
    extends: .phpunit_base
    services:
        -   name: mysql:8.0.19
            alias: mysql
            command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password", "--sql-require-primary-key=ON" ]

MariaDB 10.1:
    extends: .phpunit_base
    services:
        -   name: mariadb:10.1
            alias: mysql

MariaDB 10.5:
    extends: .phpunit_base
    services:
        -   name: mariadb:10.5
            alias: mysql

Elasticsearch 7:
    extends: .phpunit_es_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.4
    services:
        -   name: mysql:8.0.19
            alias: mysql
            command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password" ]
        -   name: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
            alias: elasticsearch
            command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]

.mink_base:
    tags:
        - m5.large
    extends: .phpunit_base
    stage: End-to-end testing
    artifacts:
        when: always
        expire_in: 1 week
        paths:
            - ${ARTIFACTS_ROOT}/**
            - build/logs/**
        reports:
            junit: ${ARTIFACTS_ROOT}/mink/*.xml
    script:
        - apk add --no-cache sudo
        - export SW_HOST=$(hostname -i)
        - make init
        - make prepare-mink
        - chown -R www-data:www-data .
        - sudo -E -u www-data vendor/bin/behat -vv --config=tests/Mink/behat.yml --format=pretty --out=std --format=junit --out=${ARTIFACTS_ROOT}/mink --tags ${MINK_TAG}
    services:
        -   name: selenium/standalone-chrome:84.0
            alias: selenium
        -   name: mailhog/mailhog
            alias: smtp
        -   name: mysql:8.0.19
            alias: mysql
            command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password" ]

Mink:
    extends: .mink_base
    image: "gitlab.shopware.com:5005/shopware/5/product/image/continuous:$IMAGE_TAG"
    parallel:
      matrix:
        - IMAGE_TAG: [ '7.4', '8.0' ]
          MINK_TAG: [ 'account', 'checkout1', 'checkout2', 'detail', 'listing', 'note', 'sitemap', 'misc', 'backend' ]
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $IMAGE_TAG != "8.0"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: manual
          allow_failure: true

Prepare Artifacts:
    tags:
        - t3.nano
    image: debian:11-slim
    stage: Build Image
    needs:
        - job: Install Required PHP Files
          artifacts: false
        - job: Install Required JS Files
          artifacts: false
    cache:
        - <<: *composer-cache
          policy: pull
        - <<: *npm-cache
          policy: pull
    script:
        - ls -lah ./*
    artifacts:
        paths:
            - '$CI_PROJECT_DIR/'
        exclude:
            - '.git'
            - '.git/**'
        expire_in: 3h
    rules:
        - if: '$CI_COMMIT_REF_PROTECTED == "true"'

Build Image:
    stage: Build Image
    needs:
        - job: Prepare Artifacts
          artifacts: false
    inherit:
        variables: false
    variables:
        UPSTREAM_PROJECT_ID: '$CI_PROJECT_ID'
        UPSTREAM_REF_NAME: '$CI_COMMIT_REF_NAME'
        UPSTREAM_COMMIT_SHA: '$CI_COMMIT_SHORT_SHA'
        UPSTREAM_JOB_NAME: 'Prepare+Artifacts'
        BASE_IMAGE_TAG: '7.4'
    trigger:
        project: shopware/5/product/image
        branch: pt-12693/add-aio-image # TODO: Change to master, once the AIO image job is finished.
    rules:
        - if: '$CI_COMMIT_REF_PROTECTED == "true"'
